# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call(`_MMGOR_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_MMGOR_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_MMGOR_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_MMGOR_rcpparma_bothproducts`, x)
}

converNaN <- function(x) {
    .Call(`_MMGOR_converNaN`, x)
}

likelihoodi <- function(b, parameters, Delta, X, Z, ni, r, blC, betadim, gammadim) {
    .Call(`_MMGOR_likelihoodi`, b, parameters, Delta, X, Z, ni, r, blC, betadim, gammadim)
}

weightfunction <- function(parameters, rules, Delta, X, Z, n, ni, r, blC, betadim, gammadim) {
    .Call(`_MMGOR_weightfunction`, parameters, rules, Delta, X, Z, n, ni, r, blC, betadim, gammadim)
}

DerivCal <- function(b, lastpar, Delta, X, Z, ni, r, blC, betadim, gammadim) {
    .Call(`_MMGOR_DerivCal`, b, lastpar, Delta, X, Z, ni, r, blC, betadim, gammadim)
}

UpdateOnce <- function(lastpar, rules, Delta, X, Z, n, ni, r, blC, betadim, gammadim) {
    .Call(`_MMGOR_UpdateOnce`, lastpar, rules, Delta, X, Z, n, ni, r, blC, betadim, gammadim)
}

MainFunc <- function(lastpar, rules, Delta, X, Z, n, ni, r, blC, betadim, gammadim, itermax, criterion) {
    .Call(`_MMGOR_MainFunc`, lastpar, rules, Delta, X, Z, n, ni, r, blC, betadim, gammadim, itermax, criterion)
}

likelihoodfunc1current <- function(b, parameters, Delta, X, Z, ni, r, blC, betadim, gammadim) {
    .Call(`_MMGOR_likelihoodfunc1current`, b, parameters, Delta, X, Z, ni, r, blC, betadim, gammadim)
}

testquadrature1current <- function(parameters, rules, Delta, X, Z, n, ni, r, blC, betadim, gammadim) {
    .Call(`_MMGOR_testquadrature1current`, parameters, rules, Delta, X, Z, n, ni, r, blC, betadim, gammadim)
}

